In [5]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 1: LU Decomposition
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
        b) Phân tích thành các thành phần Pt, L, U. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần P, L, U
============================================================================="""
print('-------------------CAU 1-----------------------')
# A = Pt.L.U
#Or P.A = L.U
#( P.Pt = P.(P^-1) = In )

#L = Lower triangle matrix, containing diagonal 1
#U = Upper triangle matrix
#P = Pivotal matrix, a pivoted unit matrix shows the steps how the original matrix is pivoted
import numpy as np
import random
from scipy.linalg import lu

def cre_mtrx(m,n,start,end):
    mtrx = []
    for i in range(m):
        row =[]
        for i in range(n):
            value = random.randint(start,end+1)
            row.append(value)
        mtrx.append(row)
    return np.array(mtrx)

mtrA = cre_mtrx(4,4,1,10)
print('Matrix A (4x4) =\n',mtrA)

print('\nLU decomposition of mtrA:')
Pt_A = lu(mtrA)[0]
print('Pt_A matrix =\n', Pt_A)
L_A = lu(mtrA)[1]
print('L_A matrix =\n', L_A)
U_A = lu(mtrA)[2]
print('U_A matrix =\n',U_A)

print('\nRecreate mtrA by using Pt@L@U =\n',Pt_A@L_A@U_A)

#For rectangular matrix (rows and columns are different in number)
print('\n--------------------------------------------------')
mtrB = cre_mtrx(3,7,1,10)
print('Matrix B (3x7) =\n',mtrB)

print('\nLU decomposition of mtrB:')
Pt_B = lu(mtrB)[0]
print('Pt_B matrix =\n', Pt_B)
L_B = lu(mtrB)[1]
print('L_B matrix =\n', L_B)
U_B = lu(mtrB)[2]
print('U_B matrix =\n',U_B)

print('\nRecreate mtrB by using Pt@L@U =\n',Pt_B@L_B@U_B)

-------------------CAU 1-----------------------
Matrix A (4x4) =
 [[ 1  9 11  1]
 [ 1  1 11 10]
 [ 5  3 10  5]
 [ 5  4  6  9]]

LU decomposition of mtrA:
Pt_A matrix =
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
L_A matrix =
 [[ 1.          0.          0.          0.        ]
 [ 0.2         1.          0.          0.        ]
 [ 0.2         0.04761905  1.          0.        ]
 [ 1.          0.11904762 -0.59166667  1.        ]]
U_A matrix =
 [[ 5.          3.         10.          5.        ]
 [ 0.          8.4         9.          0.        ]
 [ 0.          0.          8.57142857  9.        ]
 [ 0.          0.          0.          9.325     ]]

Recreate mtrA by using Pt@L@U =
 [[ 1.  9. 11.  1.]
 [ 1.  1. 11. 10.]
 [ 5.  3. 10.  5.]
 [ 5.  4.  6.  9.]]

--------------------------------------------------
Matrix B (3x7) =
 [[ 5  2  8  8  8 10  3]
 [ 1  4  2  8  9  5  8]
 [ 4  3  7  2  1  4  1]]

LU decomposition of mtrB:
Pt_B matrix =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [7]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 2: Giải hệ phương trình bằng LU Decomposition
        a) Quy về Ax = B. Sau đó giải tìm x.
        b) Phân tích thành các thành phần Pt, L, U. In kết quả.
        c) Tái tạo lại ma trận A từ các thành phần P, L, U.
============================================================================="""
print('-------------------CAU 2-----------------------')

import scipy
from scipy.linalg import lu

# def cre_mtrx(m,n,start,end): using from above cell


def cre_vector(m,start,end):
    vector = []
    for i in range(m):
        value = random.randint(start,end+1)
        vector.append(value)
    return np.array(vector)

mtrA = cre_mtrx(4,4,1,20)
print('mtrA =\n',mtrA)

vtrB = cre_vector(4,1,20)
print('\nvtrB =',vtrB)

LU_A = scipy.linalg.lu_factor(mtrA)
print('\nThe LU_A matrix = L + U - diag(L) = LU_A[0]\n',LU_A[0])
#Function scipy.linalg.lu_factor(arg) returns an array containing two sub_arrays
#The first sub_array is the LU matrix, which is equal to L + U - diag(L) (Its index is lu_factor(arg)[0])
#The second sub_array is the permutational array (Its index is lu_factor(arg)[1])

#About the permutational array, for example Per = [3,2,4,5]
#Per[0] = 3 means permutate the row[0] of unit matrix with its row[3]
#Per[1] = 2 means permutate the row[1] of unit matrix with its row[2]... and so on

#Create U matrix from np.triu(arg)
U_A = np.triu(LU_A[0]) #This functions extract the upper triangle from the LU matrix
print('\nU_A matrix created by using np.triu(LU_A[0]) =\n',U_A)


#Create L matrix with the help of np.identity()
L_A = LU_A[0] - U_A + np.identity(len(vtrB)) #np.identity returns a unit matrix having 1 along its diagonal, other positions are 0
print('\nL_A matrix created by LU_A[0] - U_A + np.identity(len(vtrB)) =\n',L_A)

##------------------------------------------------------------------------------
## Hàm tạo ma trận hoán vị P từ pivot = linalg.lu_factor(A)[1]
def permutationMatrix(pivot):
    # Khởi tạo P bằng ma trận đơn vị
    P = np.identity(len(pivot))

    # i: index; r: element
    for i, r in enumerate(pivot):
        # pivot[i] = r
        # Hoán đổi dòng r và dòng pivot[i] của ma trận I
    
        I = np.identity(len(pivot))
    
        temp    = I[i, :].copy() #Create temp to store the row i of matrix I
        I[i, :] = I[r, :]        #assign row i of I as row r of I
        I[r, :] = temp           #assign row r of I as temp (meaning the old row i)
        
        P = P.dot(I)
    return P
##------------------------------------------------------------------------------

#Create P_A from the above function, with pivot = lu_factor(matrix)[1] = or LU_A[1]
P_A = permutationMatrix(LU_A[1])
print('\nPt_A matrix created by using permutationMatrix(pivot) function =\n',P_A)

#Solve the AX = B with scipy.linalg.lu_solve(), this function requires the the result of function lu_factor(LU_A, vtrB)
print('\nThe root X of equation AX = B, solved by scipy.linalg.lu_solve(LU_A,vtrB) =\n',scipy.linalg.lu_solve(LU_A,vtrB))

-------------------CAU 2-----------------------
mtrA =
 [[ 3 18  2  5]
 [10 19  8 11]
 [ 5 11  7  1]
 [18 18  6 16]]

vtrB = [10 14  1 17]

The LU_A matrix = L + U - diag(L) = LU_A[0]
 [[18.         18.          6.         16.        ]
 [ 0.16666667 15.          1.          2.33333333]
 [ 0.27777778  0.4         4.93333333 -4.37777778]
 [ 0.55555556  0.6         0.82432432  4.31981982]]

U_A matrix created by using np.triu(LU_A[0]) =
 [[18.         18.          6.         16.        ]
 [ 0.         15.          1.          2.33333333]
 [ 0.          0.          4.93333333 -4.37777778]
 [ 0.          0.          0.          4.31981982]]

L_A matrix created by LU_A[0] - U_A + np.identity(len(vtrB)) =
 [[1.         0.         0.         0.        ]
 [0.16666667 1.         0.         0.        ]
 [0.27777778 0.4        1.         0.        ]
 [0.55555556 0.6        0.82432432 1.        ]]

Pt_A matrix created by using permutationMatrix(pivot) function =
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 