In [1]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 3: QR Decomposition
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
        b) Phân tích thành các thành phần Q và R. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần Q và R
============================================================================="""
print('-------------------CAU 3-----------------------')
#A = Q.R
# Where Q is a square matrix having orthonormal columns, meaning Qt.Q = In
#       R is an upper triangle and inversible matrix
import numpy  as np
import random       
from scipy.linalg import qr

def cre_mtrx(m,n,start,end):
    mtrx = []
    for i in range(m):
        row =[]
        for i in range(n):
            value = random.randint(start,end+1)
            row.append(value)
        mtrx.append(row)
    return np.array(mtrx)

mtrA = cre_mtrx(4,4,5,10)
print('a) Matrix A',mtrA.shape,' =\n',mtrA)

QR_A = qr(mtrA)
#The qr(matrix) function returns an array contains two matrix
#The first matrix is Q matrix, it has orthonormal columns, meaning Q.Qt = Q.inv(Q) = In
#The second matrix is R matrix, it is an upper triangle matrix and inversable
#And the A = Q.R

Q_A = QR_A[0]
print('\nb) Q_A matrix',Q_A.shape,' =\n',Q_A)

R_A = QR_A[1]
print('\nb) R_A matrix',R_A.shape,' =\n',R_A)

print('\nc) Recreate matrix A = Q.dot(R) = Q@R =\n',Q_A.dot(R_A))

-------------------CAU 3-----------------------
a) Matrix A (4, 4)  =
 [[ 6  6  7 11]
 [11 10  8  8]
 [10 10  6  8]
 [ 9 11  7  8]]

b) Q_A matrix (4, 4)  =
 [[-0.32635698 -0.05639449  0.86694811 -0.37244027]
 [-0.59832112 -0.55723124 -0.01420884  0.57558951]
 [-0.54392829 -0.09399081 -0.49814517 -0.66869958]
 [-0.48953546  0.82309096 -0.00710442  0.28779476]]

b) R_A matrix (4, 4)  =
 [[-18.38477631 -18.76552612 -13.76138582 -16.64420577]
 [  0.           2.20341317   0.34508055   0.75461194]
 [  0.           0.           2.91636414   5.38076183]
 [  0.           0.           0.          -2.5393655 ]]

c) Recreate matrix A = Q.dot(R) = Q@R =
 [[ 6.  6.  7. 11.]
 [11. 10.  8.  8.]
 [10. 10.  6.  8.]
 [ 9. 11.  7.  8.]]
