In [1]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 4: Cholesky Decomposition
        a) Tạo ma trận A(3 x 3) chứa các giá trị ngẫu nhiên trong khoảng 3 - 9
        b) Chuyển A thành ma trận vuông đối xứng theo tam giác dưới
        c) Thực hiện phân rã Cholesky, nếu có thể
============================================================================="""
#Cholesky decomposition: A = L.Lt = Ut.U
# meaning L = Ut, and Lt = U
#Only applied for square symmetrical matrix having all positive eigenvalues

#Hàm np.linalg.cholesky(matrix) mặc định trả về  ma trận L
print('-------------------CAU 4------------------------')
import numpy  as np
import random       
from numpy.linalg import cholesky
## numpy.linalg.cholesky: Default --> LOWER
## scipy.linalg.cholesky: Default --> UPPER

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

-------------------CAU 4------------------------


In [2]:
## a) Tạo ma trận A(3 x 3) chứa các giá trị ngẫu nhiên trong khoảng 3 - 9
m, n, min, max = 3, 3, 3, 9
A = create_matrix_random(m, n, min, max)

print('Ma trận A =\n',A)

Ma trận A =
 [[ 5  8  7]
 [ 4  6 10]
 [ 3  4  8]]


In [3]:
## b) Chuyển A thành ma trận vuông đối xứng theo tam giác dưới
## Điều kiện phân rã Cholesky: ma trận ĐỐI XỨNG
for i in range(A.shape[0]):
    for j in range(i):
        A[j][i] = A[i][j]

print('Ma trận A đối xứng =\n',A)


Ma trận A đối xứng =
 [[5 4 3]
 [4 6 4]
 [3 4 8]]


In [5]:
## c) Thực hiện phân rã Cholesky, nếu có thể
## Kiểm tra ma trận xác định dương
test = np.linalg.eigvalsh(A) #Trả về  một list chứa toàn bộ trị riêng của matrix A đối xứng
pos_def = np.all(test>0) #Kiểm tra xem toàn bộ trị riêng chứa trong list test có >0 hay không
                         #np.all() để apply một hàm hay lệnh gì đó vào toạn bộ phần tử  của tập hợp

if (pos_def == True):
    L = cholesky(A)
    print('\nMa trận L từ phân rã cholesky của A =\n', L)
    print('\nTái tạo ma trận A từ L.dot(L.T) =\n',L.dot(L.T))
else:
    print('\nMa trận A không thoả điều kiện xác định dương => không phân rã cholesky được')

##------------------------------------------------------------------------------
## Hàm tạo ma trận xác định dương (Bằng cách lồng những phần ở trên vào vòng lặp while)   
##------------------------------------------------------------------------------
def create_matrix_positive_definite(m, n, start, end):
    B = None
    pos_def = False
    while (pos_def == False):
        B = create_matrix_random(m,n,start,end+1)
        for i in range(B.shape[0]):
            for j in range(i):
                B[j][i] = B[i][j]
        test = np.linalg.eigvals(B)
        pos_def = np.all(test>0)
    return B
##------------------------------------------------------------------------------
B = create_matrix_positive_definite(3, 3, 3, 9) #Tạo ma trận B chắc chắn xác định dương
print('\n*** Ma trận B', B.shape, 'thỏa điều kiện XÁC ĐỊNH DƯƠNG:\n', B)

print('\nÁp dụng phân rã Cholesky cho mtrB:')
L = cholesky(B)
print('Ma trận L', L.shape, ':\n', L)

print('\nTái tạo B từ L, L_T (kiểm chứng lại phép phân rã)\n', L.dot(L.T))


Ma trận L từ phân rã cholesky của A =
 [[2.23606798 0.         0.        ]
 [1.78885438 1.67332005 0.        ]
 [1.34164079 0.95618289 2.29906813]]

Tái tạo ma trận A từ L.dot(L.T) =
 [[5. 4. 3.]
 [4. 6. 4.]
 [3. 4. 8.]]

*** Ma trận B (3, 3) thỏa điều kiện XÁC ĐỊNH DƯƠNG:
 [[11  9  9]
 [ 9 11  6]
 [ 9  6 11]]

Áp dụng phân rã Cholesky:
Ma trận L (3, 3) :
 [[ 3.31662479  0.          0.        ]
 [ 2.7136021   1.90692518  0.        ]
 [ 2.7136021  -0.71509694  1.76776695]]

Tái tạo B từ L, L_T (kiểm chứng lại phép phân rã)
 [[11.  9.  9.]
 [ 9. 11.  6.]
 [ 9.  6. 11.]]
