In [ ]:
#--------Pseudo Inverse Matrix (Ma tran gia nghich dao)------------------#

#In general, only a square matrix that can have its inverse matrix (if inversible)
#How ever, with rectangular matrix (meaning m >< n), we have a concept of Pseudo Inverse Matrix

#Call Api is the pseudo inverse matrix of rectangular matrix A

#If A.Api = I then Api is called right inverse

#If Api.A = I then Api is called left inverse

#-------------------------------------------------------------------------#

#In case A(mxn) has m>=n, then matrix (At.A) is invversible (nxm . mxn = nxn, a square matrix of smaller shape)
#        therefore, Api.A = inv(At.A).(At.A) = I
# ====> left inverse Api = inv(At.A).At


#In case A(mxn) has m=<n, then matrix (A.At) is invversible (mxn . nxm = mxm, a square matrix of smaller shape)
#        therefore, A.Api = (A.At).inv(A.At) = I
# ====> right inverse Api = At.inv(A.At)


#-----------Calculate general Api by using SVD------------------#
# Api = V.inv(S).Ut

'''------------Python function to calculate pseudo inverse matrix---------------------

Api = numpy.linalg.pinv(A)

'''

In [1]:
"""=============================================================================
Ex3: Pseudo Inverse Matrix
    Câu 3: 
        a) Tạo ma trận A(4 x 6) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
        b) Tạo ma trận giả nghịch đảo của A
============================================================================="""
print('\n---------------------Cau 3--------------------------------')
import random
import numpy as np
from numpy.linalg import inv

#a) Create A(4x6) matrix whose values range from 1 to 10 randomly
def cre_matrix(m,n,start,end):
    matrix = []
    for i in range(m):
        row = []
        for j in range(n):
            row.append(random.randint(start,end+1))
        matrix.append(row)
    return np.array(matrix)

A = cre_matrix(4,6,1,10)
print('Matrix A'+str(A.shape)+' =\n',A)

#b) Create pseudo matrix of A
print('\n********************************************************************************************')
print('1st method: create pseudo inverse matrix of A by using numpy.linalg.pinv(A)')
Api = np.linalg.pinv(A)
print('\nPseudo inverse matrix mtrApi of A =',Api)
print('\nCheck if Api.A = In =\n',Api@A)
print('\nCheck if A.Api = Im =\n',A@Api)

print('\n********************************************************************************************')
print('2nd method: using SVD, Api = V.inv(S).Ut to create pseudo inverse matrix')
U,s,Vt = np.linalg.svd(A)

#Do SVD analysis of A
print('\nThe U'+str(U.shape)+' orthogonal matrix of A =\n',U)
print('\nThe s sqrt(eigenvalues) of A =\n',s)
print('\nThe Vt'+str(Vt.shape)+' normalized orthogonal matrix of A =\n',Vt)

#Since S(6x4) will not be a square matrix, so we have to create the inverse S matrix manually by following codes
invS = np.zeros(A.T.shape) #create a zero matrix have the same shape of matrix transpose(A) = 6x4
                           #The shape of Vt is 6x6, so the V is also 6x6
                        #Therefore we have to create a 6x4 invS matrix to be able to multiply the matrix V in V.invS.Ut
                        #That's why we use np.zeros(A.T.shape)

d = 1.0 / s #calculate the inverse of s values
invS[:len(s),:len(s)] = np.diag(d) #len(s) = 4, so this command is to add the s values into first 4 diagonal positons
print('\nThe inverse S matrix of A =\n',invS)

#Api = V.inv(S).Ut
Api = (Vt.T).dot(invS).dot(U.T)

print('\nThe pseudo inverse matrix Api = (Vt.T).dot(inv(S)).dot(U.T) =\n',Api)
print('\nCheck if Api.A = In =\n',Api@A)
print('\nCheck if A.Api = Im =\n',A@Api)


---------------------Cau 3--------------------------------
Matrix A(4, 6) =
 [[ 5 11  2  9  2  3]
 [11  4 10  9  2  5]
 [ 8  2  5  6  4  7]
 [ 9  3 10  8  9  2]]

********************************************************************************************
1st method: create pseudo inverse matrix of A by using numpy.linalg.pinv(A)

Pseudo inverse matrix mtrApi of A = [[-0.01904974  0.04566095  0.01985468 -0.0176757 ]
 [ 0.08068972 -0.01106598 -0.03868499 -0.00138489]
 [-0.03873884  0.09181857 -0.09108997  0.02815957]
 [ 0.03167374  0.01490235 -0.01564176  0.00222921]
 [ 0.00825998 -0.14768655  0.0705111   0.11030258]
 [-0.00548137 -0.04298805  0.16939837 -0.06445829]]

Check if Api.A = In =
 [[ 4.06777864e-01 -4.02211200e-02  3.41026402e-01  2.17223329e-01
  -2.64402035e-02  2.74786879e-01]
 [-4.02211200e-02  7.61798368e-01 -1.56554225e-01  3.83424601e-01
  -2.79565192e-02 -8.68254541e-02]
 [ 3.41026402e-01 -1.56554225e-01  6.66853834e-01  1.56454266e-01
  -4.76430639e-03 -2.38434330e-