In [1]:
import numpy as np

In [2]:
arr_1 = np.arange(10) #Phát sinh mảng từ 0 đến 9
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr_1 = np.arange(1,20) #Mảng từ 1 - 19
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
arr_1 = np.arange(0,10,2) #0 - 8 với step là 2
arr_1

array([0, 2, 4, 6, 8])

In [5]:
arr_2 = np.asarray((1,4,6)) #Truyền vào tuple để tạo array
arr_2

array([1, 4, 6])

In [6]:
arr_3 = np.ones((3,2),dtype=int) #Tạo ma trận 1, gồm 3 dòng và 2 cột
arr_3

array([[1, 1],
       [1, 1],
       [1, 1]])

In [7]:
arr_4 = np.zeros((5,2)) #Tạo ma trận 0 với 5 dòng 2 cột
arr_4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
arr_5 = np.linspace(1,50,5) #Tạo ma trận gồm 5 phần tử, đầu là 1, cuối là 50, chênh lệch của các phần tử bằng nhau
arr_5

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [9]:
arr_6 = np.linspace(1,50,5,endpoint=False) #Cũng giống cái trên, nhưng không lấy endpoint là 50
arr_6

array([ 1. , 10.8, 20.6, 30.4, 40.2])

In [10]:
arr_7 = np.linspace(1,40,5,retstep=True) #Cũng giống linspace thường, trả về giá trị bước nhảy giữa các phần tử
arr_7

(array([ 1.  , 10.75, 20.5 , 30.25, 40.  ]), 9.75)

In [11]:
arr_8 = np.random.randint(10,size=(3,4)) #Tạo ma trận 3 dòng 4 cột, mỗi phân tử  số nguyên ngẫu nhiên từ 0-9 số 
arr_8

array([[2, 9, 4, 3],
       [6, 4, 9, 5],
       [5, 8, 9, 1]])

In [12]:
arr_9 = np.random.rand(3,2) #Tạo mtr 3 dòng 2 cột, mỗi phần tử ngẫu nhiên từ 0 đến 1 (float)
arr_9

array([[0.60889413, 0.32031624],
       [0.8078073 , 0.4142662 ],
       [0.47306101, 0.30185451]])

In [13]:
arr_10 = np.arange(15,25)
print(arr_10)
arr_10.shape #Trả về tuple (số hàng, số cột) chứa thông tin về số hàng và cột của array đó

[15 16 17 18 19 20 21 22 23 24]


(10,)

In [14]:
arr_11 = np.random.randint(20,size=(5,4))
print(arr_11)
arr_11.shape

[[16 19 18  1]
 [17 12 17  3]
 [11 11 16 10]
 [17 16 10 17]
 [ 4  5  2  6]]


(5, 4)

In [15]:
arr_11.sum(axis=1) #Tổng theo hàng

array([54, 49, 48, 60, 17])

In [16]:
arr_11.sum(axis=0) #Tổng theo cột

array([65, 63, 63, 37])

In [18]:
arr_1 = np.arange(12)
print(arr_1)

arr_2 = arr_1.reshape(3,4) #Từ arr_1, reshape lại để tạo ma trận arr_2 (3 dòng, 4 cột)
print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
arr_2[:2,:2] #Tham chiếu đến hàng và cột mong muốn

array([[0, 1],
       [4, 5]])

In [21]:
arr_2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [22]:
print(arr_1)
print(np.std(arr_1)) #Tính độ lệch chuẩn của các dữ liệu trong arr_1

[ 0  1  2  3  4  5  6  7  8  9 10 11]
3.452052529534663


In [27]:
arr_ex = arr_1.reshape(2,6)
print(arr_ex)
print(np.corrcoef(arr_ex[0],arr_ex[1])) #Tính hệ số tương quan giữa các phần tử trong arr_ex[0] và arr_ex[1]
                                        #kết quả trả về  là [[coreff 0-0 = 1, corref 0-1], 
                                        #                     [corref 1-0, coref1-1 = 1]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[1. 1.]
 [1. 1.]]
