In [1]:
import numpy as np

In [2]:
#Đọc tập tin heights_1.txt vào dưới dạng array (chiều cao của vđv bóng rổ, đơn vị là inch)
f = open('heights_1.txt')
data_heights = f.read() #Đọc dữ liệu trong tập tin, trả về dạng string
f.close
print(data_heights)

[74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73,  73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72,  73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75,    73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72

In [3]:
lst_heights = eval(data_heights) #eval() đánh giá chuỗi heights, thấy giống list nên convert sang list luôn

In [4]:
arr_heights = np.array(lst_heights) #CHuyển lst thành array

In [5]:
arr_heights.shape

(1015,)

In [6]:
arr_heights[0:10] #Xem 10 người đầu tiên, từ 0 đến cận 10 (là 9)

array([74, 74, 72, 72, 73, 69, 69, 71, 76, 71])

In [7]:
arr_heights[-10:] #Xem 10 người cuối cùng

array([75, 69, 75, 72, 75, 73, 74, 75, 75, 73])

In [8]:
#Thống kê đơn giản
print('Average heights:',np.mean(arr_heights))  #Không theo hướng đối tượng, dùng function
print('Average heights:',arr_heights.mean())   #Theo kiểu hướng đối tượng (Object oriented), dùng method

Average heights: 73.6896551724138
Average heights: 73.6896551724138


In [9]:
#Đổi chiều cao từ inch sang mét (1 inch = 0.0254 mét)
arr_met = arr_heights*0.0254
arr_met

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [13]:
print('mean:',arr_met.mean())
print('max:',arr_met.max())
print('min:',arr_met.min())
print('median:',np.median(arr_met)) #Vì class array không có method median nên phải dùng hàm numpy.median()

mean: 1.8717172413793102
max: 2.1082
min: 1.7018
median: 1.8796


In [11]:
arr_met[arr_met <= 1.8] #Truy xuất chiều cao <= 1.8 mét

array([1.7526, 1.7526, 1.7526, 1.778 , 1.7526, 1.778 , 1.778 , 1.778 ,
       1.778 , 1.778 , 1.7272, 1.7272, 1.7526, 1.778 , 1.778 , 1.778 ,
       1.778 , 1.7526, 1.778 , 1.778 , 1.778 , 1.7526, 1.778 , 1.778 ,
       1.7526, 1.778 , 1.778 , 1.778 , 1.778 , 1.778 , 1.778 , 1.7526,
       1.7526, 1.7526, 1.778 , 1.7526, 1.778 , 1.778 , 1.778 , 1.778 ,
       1.778 , 1.778 , 1.7526, 1.778 , 1.778 , 1.7526, 1.778 , 1.7526,
       1.778 , 1.778 , 1.7526, 1.778 , 1.778 , 1.778 , 1.778 , 1.778 ,
       1.7272, 1.778 , 1.7272, 1.7526, 1.778 , 1.7272, 1.778 , 1.7272,
       1.778 , 1.778 , 1.778 , 1.778 , 1.778 , 1.778 , 1.7272, 1.7526,
       1.778 , 1.778 , 1.7018, 1.7018, 1.778 , 1.778 , 1.7526])

In [12]:
arr_met[arr_met > 2.0] #Truy xuất chiều cao > 2 mét

array([2.0066, 2.0574, 2.0066, 2.032 , 2.0066, 2.0066, 2.032 , 2.032 ,
       2.0066, 2.0066, 2.032 , 2.0066, 2.0066, 2.0828, 2.0066, 2.0066,
       2.032 , 2.0066, 2.0066, 2.0574, 2.0066, 2.0828, 2.1082, 2.0066])

In [15]:
#Toán tử  and: &
#Toán tử  or: |
#Toán tử not: ~

arr_met[(arr_met < 2.0) & (arr_met > 1.8)]

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.8034, 1.9304, 1.8034,
       1.8542, 1.8542, 1.8796, 1.8796, 1.8542, 1.905 , 1.9812, 1.9304,
       1.8796, 1.9304, 1.8288, 1.8034, 1.905 , 1.9558, 1.8796, 1.8542,
       1.8796, 1.9812, 1.8542, 1.905 , 1.8542, 1.905 , 1.905 , 1.8796,
       1.8034, 1.8796, 1.8542, 1.8542, 1.9304, 1.8796, 1.8796, 1.8288,
       1.9558, 1.8796, 1.8542, 1.905 , 1.9304, 1.9304, 1.9812, 1.8796,
       1.8796, 1.9304, 1.9558, 1.9812, 1.905 , 1.9558, 1.905 , 1.9304,
       1.8796, 1.8288, 1.8288, 1.905 , 1.8542, 1.8542, 1.8542, 1.9304,
       1.8034, 1.8288, 1.905 , 1.905 , 1.905 , 1.905 , 1.8796, 1.9812,
       1.8034, 1.8542, 1.9304, 1.8796, 1.8796, 1.905 , 1.8542, 1.9304,
       1.8796, 1.8796, 1.8542, 1.8288, 1.8796, 1.8542, 1.8796, 1.8288,
       1.8542, 1.8288, 1.8542, 1.905 , 1.905 , 1.8542, 1.8288, 1.8288,
       1.9304, 1.8796, 1.8288, 1.9558, 1.8796, 1.9558, 1.905 , 1.9304,
       1.8796, 1.8796, 1.905 , 1.9812, 1.8542, 1.8542, 1.8796, 1.905 ,
      

In [54]:
arr_met5 = arr_met[0:5] #tạo mảng gồm 5 giá trị đầu của arr_met
arr_met5

array([1.8288, 1.8288, 1.8542, 1.8796, 1.8796])

In [46]:
print(arr_met5)
print(np.append(arr_met5,1.93)) #Thêm giá trị 1.93 vào cuối arr_met5

[1.8796 1.8796 1.8288 1.8288 1.8542]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.93  ]


In [47]:
print(arr_met5)
print(np.append(arr_met5,[1.75,1.82,1.91])) #Thêm 3 giá trị trên vào cuối arr_met5

[1.8796 1.8796 1.8288 1.8288 1.8542]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.75   1.82   1.91  ]


In [49]:
print(arr_met5)
print(np.insert(arr_met5,1,1.65)) #Thêm giá trị 1.65 vào arr_met5 ở index = 1

[1.8796 1.8796 1.8288 1.8288 1.8542]
[1.8796 1.65   1.8796 1.8288 1.8288 1.8542]


In [50]:
print(arr_met5)
print(np.delete(arr_met5,2)) #Xoá giá trị có index = 2 của arr_met5

[1.8796 1.8796 1.8288 1.8288 1.8542]
[1.8796 1.8796 1.8288 1.8542]


In [51]:
condition = arr_met5 < 1.5 #Kiểm tra từng giá trị với điều kiện, trả về array chứa từng kết quả boolean 
condition

array([False, False, False, False, False])

In [53]:
print(arr_met5)
print(np.sort(arr_met5)) #Xếp tăng dần

[1.8288 1.8288 1.8542 1.8796 1.8796]
[1.8288 1.8288 1.8542 1.8796 1.8796]


In [55]:
print(arr_met5)
print(np.sort(arr_met5)[::-1]) #Xếp giảm dần

[1.8288 1.8288 1.8542 1.8796 1.8796]
[1.8796 1.8796 1.8542 1.8288 1.8288]
