In [1]:
import numpy as np

In [2]:
f = open('weights_1.txt') #Khối lượng cầu thủ bóng chày, đơn vị pounds
data_w = f.read()
f.close

lst_w = eval(data_w)
arr_lbs = np.array(lst_w)

In [3]:
arr_lbs

array([180, 215, 210, ..., 205, 190, 195])

In [4]:
#Chuyển đổi sang kg (*0.453592)
arr_kg = arr_lbs*0.453592
print(arr_kg)

[81.64656 97.52228 95.25432 ... 92.98636 86.18248 88.45044]


In [6]:
#shape arr_kg
arr_kg.shape

(1015,)

In [7]:
#10 ptu dau
arr_kg[:10]

array([ 81.64656 ,  97.52228 ,  95.25432 ,  95.25432 ,  85.275296,
        79.832192,  94.800728,  90.7184  , 104.779752,  81.64656 ])

In [8]:
#10 ptu cuoi
arr_kg[-10:]

array([104.32616,  86.18248,  99.79024,  81.64656,  92.98636,  86.18248,
        81.64656,  92.98636,  86.18248,  88.45044])

In [11]:
#Thống kê
print('mean weight kg:',arr_kg.mean())
print('median weight kg:',np.median(arr_kg))
print('min weight kg:',arr_kg.min())
print('max weight kg:',arr_kg.max())

mean weight kg: 91.33019058916256
median weight kg: 90.7184
min weight kg: 68.0388
max weight kg: 131.54167999999999


In [12]:
#sort tang
np.sort(arr_kg)

array([ 68.0388  ,  68.0388  ,  68.0388  , ..., 122.46984 , 126.098576,
       131.54168 ])

In [13]:
#sort giam
np.sort(arr_kg)[::-1]

array([131.54168 , 126.098576, 122.46984 , ...,  68.0388  ,  68.0388  ,
        68.0388  ])