In [1]:
import numpy as np

In [2]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
arr_3d[1,0]

array([7, 8, 9])

In [5]:
arr_3d[1,0,1]

8

In [7]:
arr_3d.shape

(2, 2, 3)

In [8]:
arr_3d.sum() #Tát cả phần tử

78

In [9]:
arr_3d[1].sum() # = 7+8+9+10+11+12

57

In [10]:
arr_3d[1,0].sum() # = 7+8+9

24