In [1]:
#Numpy = numeric python, thư viện chuyên dùng để xử lý số, tạo mảng (array)
#Mảng có thể  một chiều hoặc nhiều chiều
#Cấc giá trị trong mảng phải CÙNG kiểu dữ liệu

In [2]:
import numpy as np

In [3]:
#Tạo array 1 chiều:
arr_1 = np.array([9.0, 7.5, 6.8, 8.9, 7.5])

In [4]:
arr_1

array([9. , 7.5, 6.8, 8.9, 7.5])

In [5]:
arr_1.dtype #Kiểm tra kiểu dữ liệu

dtype('float64')

In [6]:
print('mean:', arr_1.mean()) #Trả về giá trị trung bình mean
print('max:',arr_1.max())
print('min:',arr_1.min())

mean: 7.94
max: 9.0
min: 6.8


In [7]:
arr_1 + 0.5 #Cộng 0.5 cho tất cả phần tử của arr_1, giá trị của arr_1 vẫn không đổi, nó chỉ xuất ra kết quả phép tính

array([9.5, 8. , 7.3, 9.4, 8. ])

In [8]:
arr_2 = arr_1 + 0.5 #Gán arr_2 bằng phép tính arr_1 + 0/5
print(arr_2)

[9.5 8.  7.3 9.4 8. ]


In [9]:
print('arr_1:',arr_1) #Giá trị của arr_1 vẫn không đổi
print('arr_2:',arr_2)

arr_1: [9.  7.5 6.8 8.9 7.5]
arr_2: [9.5 8.  7.3 9.4 8. ]


In [10]:
arr_1.sort() #Sắp xếp tăng dần, làm thay đổi trật tự trong dãy arr_1
print(arr_1)

[6.8 7.5 7.5 8.9 9. ]


In [11]:
arr_1[::-1] #Xếp giảm dần bằng cách đảo ngược thứ tự dãy tăng dần, lưu ý chỉ thực hiện cách này sau khi xếp tăng dần
            #Cách này không làm thay đổi trật tự arr_1 ban đầu, chỉ show kết quả

array([9. , 8.9, 7.5, 7.5, 6.8])

In [17]:
print(arr_1)
arr_1[1] #Tham chiếu đến phần tử  thứ 2 (có index = 1)

[6.8 7.5 7.5 8.9 9. ]


7.5

In [14]:
arr_1[3]

8.9

In [15]:
arr_1[-1]

9.0

In [19]:
arr_1[-2]

8.9