In [1]:
import numpy as np
"""=============================================================================
Ex2: MATRICES
    Câu 1:
        a) Viết hàm cal_matrices(op, m1, m2) với:
            op là một trong các toán tử +, -, *, /
            u và v là 2 ma trận (numpy array) 
        b) Thực hiện tính toán theo các toán tử với 2 ma trận được truyền vào.
============================================================================="""
print('-------------------------CAU 1---------------------------------')

def cals_matrixs (op,u,v):
    if op == '+':
        result = u + v
    elif op == '-':
        result = u - v
    elif op == '*':
        result = u * v
    else:
        result = None
    return result

m1 = np.array([[1,2],[3,4]])
print('Matrix m1 =\n',m1)
print()
m2 = np.array([[5,6],[7,8]])
print('Matrix m2 =\n',m2)
print()

print('m1 + m2 =\n',cals_matrixs('+',m1,m2))
print('\nm1 - m2 =\n',cals_matrixs('-',m1,m2))
print('\nm1 * m2 =\n',cals_matrixs('*',m1,m2)) #Not the .dot() or @

-------------------------CAU 1---------------------------------
Matrix m1 =
 [[1 2]
 [3 4]]

Matrix m2 =
 [[5 6]
 [7 8]]

m1 + m2 =
 [[ 6  8]
 [10 12]]

m1 - m2 =
 [[-4 -4]
 [-4 -4]]

m1 * m2 =
 [[ 5 12]
 [21 32]]


In [2]:
"""=============================================================================
Ex2: MATRICES
    Câu 2:
        Cho các ma trận A = [[1, 3, 3], [4, 5, 6], [7, 8, 9]] và 
                ma trận B = [[2, 3], [6, 8], [5, 7]]
        Thực hiện nhân 2 ma trận. 
============================================================================="""
print('--------------------CAU 2----------------------------')
mA = np.array([[1, 3, 3], [4, 5, 6], [7, 8, 9]])
mB = np.array([[2, 3], [6, 8], [5, 7]])
print('mA =\n',mA)
print('\nmB =\n',mB)
print('\nmA.dot(mB) =\n',mA.dot(mB))
print('\nmA @ mB =\n',mA@mB)

#Để nhân ma trận có thể dùng mA.dot(mB) hoặc mA@mB, cho kết quả như nhau

--------------------CAU 2----------------------------
mA =
 [[1 3 3]
 [4 5 6]
 [7 8 9]]

mB =
 [[2 3]
 [6 8]
 [5 7]]

mA.dot(mB) =
 [[ 35  48]
 [ 68  94]
 [107 148]]

mA @ mB =
 [[ 35  48]
 [ 68  94]
 [107 148]]
