In [5]:
print('-----------CAU 1-----------------')
"""=============================================================================
Ex3: VECTORS, MATRIX, SCALAR
    Câu 1:
        a) Viết hàm cal_scalar_mult(v, b) với:
            v là vector hoặc ma trận (numpy array)
            b là scalar.
        b) Hãy thực hiện tính toán theo vector/ma trận/scalar được truyền vào.
NHÂN VECTOR VỚI MỘT SỐ  VÔ HƯỚNG
============================================================================="""
import numpy as np
#------------Tạo hàm nhân vô hướng
def cals_mult_scalar (v,n):
    return v * n

#---------------Nhân ma trận với một số vô hướng
matrix = np.array([[1,3,9],[2,8,5]])
print('Matrix =\n',matrix)
print('\nMatrix * 3 =\n',cals_mult_scalar(matrix,3))

#-------------------Nhân vector với một số vô hướng
v = np.array([1, 7, 3, 5, 2, 4])
print('\nVector v =',v)
print('Vector v * 5 =', cals_mult_scalar(v, 5))

-----------CAU 1-----------------
Matrix =
 [[1 3 9]
 [2 8 5]]

Matrix * 3 =
 [[ 3  9 27]
 [ 6 24 15]]

Vector v = [1 7 3 5 2 4]
Vector v * 5 = [ 5 35 15 25 10 20]


In [ ]:
"""=============================================================================
Ex3: VECTORS, NATRIX, SCALAR
    Câu 2:
        a) Viết hàm cho phép người dùng nhập vào 1 ma trận A[mxn].
        b) Viết hàm cho phép người dùng nhập vào 1 vector v[n].
        c) Thực hiện phép nhân ma trận với vector trên.
============================================================================="""
print('\n-----------CAU 2-----------------')
import numpy as np

#-------------Hàm tạo vector--------------------------#
def create_vector():
    v = [] #Tạo một list rỗng
    i=1
    br=False
    try:
        length = eval(input('Input the size of vector: '))
    except Exception:
        while True:
            try:
                length=eval(input('>>>Error, the size of vector must be a number, input again: '))
            except Exception: continue
            else: break
    for i in range(length):
        element = input('Input element ('+str(i)+') of vector: ')
        try:
            v.append(eval(element)) #eval để chuyển string thành số, rồi truyền vào v
        except Exception:
            while True:
                element=input('>>>Error, the element of vector must be a number, input again: ')
                try:
                    v.append(eval(element))
                except Exception: continue
                else: break
    return np.array(v) #Chuyển list v thành vector v

#------------------ Hàm tạo matrix--------------

def creat_matrix():
    try:
        rows = eval(input('\nInput the number of rows of matrix: '))
    except Exception:
        while True:
            try:
                rows = eval(input('>>>Error, the number of rows of matrix must be a number, input again: '))
            except Exception: continue
            else: break
    
    try:
        columns = eval(input('Input the number of columns of matrix: '))
    except Exception:
        while True:
            try:
                columns = eval(input('>>>Error, the number of columns of matrix must be a number, input again: '))
            except Exception: continue
            else: break
    
    m = []

    for i in range(rows): #Nhập phần tử cho một hàng, rồi kết hợp các hàng với nhau thành một matrix
        element = []
        for j in range(columns):
            try:
                value = (eval(input('Input the element ('+str(i)+','+str(j)+') of matrix: ')))
            except Exception:
                while True:
                    try:
                        value = (eval(input('>>>Error, the element ('+str(i)+','+str(j)+') must be a number, input again: ')))
                    except Exception: continue
                    else: break
            element.append(value)
        m.append(element)
    
    return np.array(m)

#----------------Giải bài-----------------#
v = create_vector()
print('Vector v =',v)

mtrx = creat_matrix()
print("Matrix =\n",mtrx)

try:
    print('\nMatrix @ v =',mtrx@v)
except Exception:
    while True:
        print('>>>Error, the columns number of matrix must be euqal to the lenght of vector, please adjust the input.\n')
        v = create_vector()
        print('\nVector v =',v)
        mtrx = creat_matrix()
        print("\nMatrix =\n",mtrx)
        try:
            print('\nMatrix @ v =',mtrx@v)
        except Exception: continue
        else: break

In [6]:
"""=============================================================================
Ex3: VECTORS, NATRIX, SCALAR
    Câu 4:
        a) Tạo ma trận X(mxn) có giá trị trong khoảng 0-11.
        b) Tìm ma trận chuyển vị của X.
        c) Tính X_T.X.
============================================================================="""
print('-----------------CAU 4---------------------')
import numpy  as np
from random import randint

#--------Create random matrix----------#
def cre_matrix_random(m,n,start,end):
    matrix = []
    for i in range(m):
        row = []
        for j in range(n):
            value = randint(start,end+1)
            row.append(value)
        matrix.append(row)
    return np.array(matrix)

#----------Solve problem-------#
try:
    m = eval(input('\nInput the number of rows of matrix: '))
except Exception:
    while True:
        try:
            m = eval(input('>>>Error, the number of rows of matrix must be a number, input again: '))
        except Exception: continue
        else: break
    
try:
    n = eval(input('Input the number of columns of matrix: '))
except Exception:
    while True:
        try:
            n = eval(input('>>>Error, the number of columns of matrix must be a number, input again: '))
        except Exception: continue
        else: break

mtrX = cre_matrix_random(m,n,0,11)
print('mtrX =\n',mtrX)

print('\nmtrX_T (transpose) =\n',mtrX.transpose())

print('\nmtrX_T @ mtrX =\n',mtrX.transpose()@mtrX)

-----------------CAU 4---------------------



Input the number of rows of matrix:  4
Input the number of columns of matrix:  5


mtrX =
 [[ 3  9  1  6  7]
 [ 9  2  8  3 12]
 [ 6  8 10  2  6]
 [11  4 10  9  2]]

mtrX_T (transpose) =
 [[ 3  9  6 11]
 [ 9  2  8  4]
 [ 1  8 10 10]
 [ 6  3  2  9]
 [ 7 12  6  2]]

mtrX_T @ mtrX =
 [[247 137 245 156 187]
 [137 165 145 112 143]
 [245 145 265 140 183]
 [156 112 140 130 108]
 [187 143 183 108 233]]


In [ ]:
"""=============================================================================
Ex3: VECTORS, NATRIX, SCALAR
    Câu 5:
        a) Tạo ma trận vuông A(mxm) với các giá trị ngẫu nhiên từ 1 đến 4.
        b) Tạo ma trận nghịch đảo của A
        c) Tính A.B
============================================================================="""
print('-----------------CAU 5---------------------')
import numpy  as np
from random import randint
from numpy.linalg import inv #Import function inv to create inverse matrix
#----------Function for square matrix
def cre_sqrmtrx_random(m,start,end):
    sqrmtr = []
    for i in range(m):
        row = []
        for j in range (m):
            value = randint(start,end+1)
            row.append(value)
        sqrmtr.append(row)
    return np.array(sqrmtr)

#-----------Solve
try:
    m = eval(input('\nInput the level of square matrix: '))
except Exception:
    while True:
        try:
            m = eval(input('>>>Error, the level of square matrix must be a number, input again: '))
        except Exception: continue
        else: break

sqrmtrA = cre_sqrmtrx_random(m,1,4)
print('\nSquare matrix A =\n',sqrmtrA)

invA = np.around(inv(sqrmtrA),3) #Create inverse matrix of A
                                 #np.around() to round the decimal numbers
print('\nInverse matrix of A =\n',invA)

print('sqrmtrA @ invA =\n', np.around(sqrmtrA@invA))

In [ ]:
"""=============================================================================
Ex3: VECTORS, NATRIX, SCALAR
    Câu 6:
        a) Tạo ma trận vuông A(mxm) với các giá trị ngẫu nhiên từ 5 đến 10.
        b) Tính tổng các phần tử trên đường chéo chính (trace). 
        c) Tính định thức của A.
        d) Tính hạng của A.
============================================================================="""
print('-----------------CAU 6---------------------')

import numpy as np
from numpy.linalg import det, matrix_rank
from random import randint

def cre_sqrmtr_random (m,start,end):
    sqrmtr = []
    for i in range(m):
        row = []
        for j in range (m):
            value = randint(start,end+1)
            row.append(value)
        sqrmtr.append(row)
    return np.array(sqrmtr)

try:
    m = eval(input('\nInput the level of square matrix: '))
except Exception:
    while True:
        try:
            m = eval(input('>>>Error, the level of square matrix must be a number, input again: '))
        except Exception: continue
        else: break

mtrA = cre_sqrmtr_random(m,5,10)
print('\nSquare matrix A =\n',mtrA)

print('\nTrace of matrix A =',np.trace(mtrA))
print('\nDet of matrix A =',det(mtrA))
print('\nRank of matrix A =',matrix_rank(mtrA))

In [ ]:
"""=============================================================================
Ex3: VECTORS, NATRIX, SCALAR
    Câu 7:
        a) Tạo ma trận vuông A(mxm) với các giá trị ngẫu nhiên từ 1 đến 6.
        b) Tạo 1 vector B[n] với giá trị ngẫu nhiên từ 1 đến 3. 
        c) Giải hệ phương trình Ax = B.
============================================================================="""
import numpy as np
from numpy.linalg import solve, inv
from random import randint

def cre_sqrmtr_random (m,start,end):
    sqrmtr = []
    for i in range(m):
        row = []
        for j in range (m):
            value = randint(start,end+1)
            row.append(value)
        sqrmtr.append(row)
    return np.array(sqrmtr)

def cre_vtr (n,start,end):
    vtr = []
    for i in range(n):
        value = randint(start,end+1)
        vtr.append(value)
    return np.array(vtr)

try:
    m = eval(input('\nInput the level of square matrix A: '))
except Exception:
    while True:
        try:
            m = eval(input('>>>Error, the level of square matrix must be a number, input again: '))
        except Exception: continue
        else: break

try:
    n = eval(input('\nInput the size of vector B: '))
except Exception:
    while True:
        try:
            m = eval(input('>>>Error, the level of square matrix must be a number, input again: '))
        except Exception: continue
        else: break

mtrA = cre_sqrmtr_random(m,1,6)
print('\nSquare matrix A =\n',mtrA)

vtrB = cre_vtr(n,1,3)
print('\nVector B =\n',vtrB)

print('\nSolve Ax = B with inverse matrix:')
print('X = inv(A).dot(B) =',inv(mtrA).dot(vtrB))

print('\nSolve Ax = B with np.lnalg.solve():')
print('X = np.lnalg.solve(mtrA,vtrB) =',solve(mtrA,vtrB))