In [1]:
"""=============================================================================
Ex2: EIGENDECOMPOSITION
    Câu 2:
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 9
        b) Tạo ma trận đối xứng B = A @ A.T
        c) Phân tích eigenvalues và eigenvectors của B
============================================================================="""
#mtrA = eigenvectors @ diag(eigenvalues) @ transpose(eigenvectors)
#or mtrA = eigenvectors @ diag(eigenvalues) @ inv(eigenvectors)

#This only works if all eigenvalues of A are > 0

print('\n--------------------------CAU 2----------------------------------------')
import numpy as np
import random
from numpy.linalg import eig

def cre_matrix(m,n,start,end):
    matrix = []
    for i in range(m):
        row = []
        for j in range(n):
            value = random.randint(start,end+1)
            row.append(value)
        matrix.append(row)
    return np.array(matrix)

#a) Create matrix A(4x4) whose values range from 1 to 9
mtrA = cre_matrix(4,4,1,9)
print('Matrix A',mtrA.shape,'=\n',mtrA)

#b) Create matrix B = A @ A.T (THIS KIND OF MATRIX CAN ALWAYS APPLY Eigendecomposition)
mtrB = mtrA@np.transpose(mtrA) #mtrA @ mtrA.T
print('\nMatrix B = mtrA @ mtrA_T =\n',mtrB)
print()

#c) Analyze eigenvalues and eigenvectors of matrix B = A @ A.T
eigvalB,eigvectB = eig(mtrB)

for j in range(len(eigvalB)):
    r = eigvalB[j].real
    i = eigvalB[j].imag
    print('Eigenvalues['+str(j)+'] of mtrB = ('+str(r)+' ; '+str(i)+')')

print('\nEigenvectos of mtrB =\n',eigvectB)


--------------------------CAU 2----------------------------------------
Matrix A (4, 4) =
 [[ 6 10  4  7]
 [ 7  1  1  6]
 [ 3  2  8  6]
 [ 2  4  4  2]]

Matrix B = mtrA @ mtrA_T =
 [[201  98 112  82]
 [ 98  87  67  34]
 [112  67 113  58]
 [ 82  34  58  40]]

Eigenvalues[0] of mtrB = (368.1259085769249 ; 0.0)
Eigenvalues[1] of mtrB = (1.0201909792254973 ; 0.0)
Eigenvalues[2] of mtrB = (36.87118014157712 ; 0.0)
Eigenvalues[3] of mtrB = (34.98272030227285 ; 0.0)

Eigenvectos of mtrB =
 [[ 0.71232641  0.32038221 -0.49543403  0.3801203 ]
 [ 0.4015312  -0.22977457 -0.22849815 -0.85660081]
 [ 0.48768428  0.27174888  0.82710441 -0.06492214]
 [ 0.3058232  -0.87790172  0.13502595  0.34282465]]
